[package]
name = "rucket"
version = "0.1.0"
authors = ["Edward Yang <edward.yang6771@gmail.com>"]
build = "build.rs"

[dependencies]
lazy_static = "*"
libc = "*"
simd = { git = "https://github.com/huonw/simd" }

[lib]
name = "rmapcollision"
crate-type = ["dylib"]
