[package]
name = "rucket"
version = "0.1.0"
authors = ["Edward Yang <edward.yang6771@gmail.com>"]
build = "build.rs"

[dependencies]
lazy_static = "*"

[lib]
name = "rmapcollision"
crate-type = ["dylib"]
